import streamlit as st
import pandas as pd
import folium
from streamlit_folium import st_folium
from fpdf import FPDF
import io

# ===============================
# 1. Генератор PDF-звіту
# ===============================
class RadiationPDF(FPDF):
    def header(self):
        self.set_font('Helvetica', 'B', 14)
        self.cell(0, 10, 'Radiation Monitoring Report', ln=True, align='C')
        self.set_font('Helvetica', '', 10)
        self.cell(0, 10, 'Generated by Radiation Mapping Web App', ln=True, align='C')
        self.ln(10)

    def footer(self):
        self.set_y(-15)
        self.set_font('Helvetica', 'I', 8)
        self.cell(0, 10, f'Page {self.page_no()}', align='C')

def generate_pdf_report(df):
    pdf = RadiationPDF()
    pdf.add_page()
    
    pdf.set_font('Helvetica', 'B', 10)
    pdf.set_fill_color(240, 240, 240)
    
    headers = ['Date/Time', 'Lat', 'Lon', 'Value', 'Unit']
    widths = [45, 35, 35, 35, 40]
    
    for i in range(len(headers)):
        pdf.cell(widths[i], 10, headers[i], 1, 0, 'C', True)
    pdf.ln()

    pdf.set_font('Helvetica', '', 9)
    for _, r in df.iterrows():
        val_clean = f"{float(r['value']):.5f}".rstrip('0').rstrip('.')
        pdf.cell(widths[0], 10, str(r['time']), 1)
        pdf.cell(widths[1], 10, str(round(r['lat'], 5)), 1)
        pdf.cell(widths[2], 10, str(round(r['lon'], 5)), 1)
        pdf.cell(widths[3], 10, val_clean, 1)
        pdf.cell(widths[4], 10, str(r['unit']), 1)
        pdf.ln()
    
    return pdf.output(dest='S').encode('latin1', 'replace')

# ===============================
# 2. Налаштування сторінки
# ===============================
st.set_page_config(page_title="Radiation System", layout="wide")
st.markdown("<style>#MainMenu, footer, header {visibility: hidden;}</style>", unsafe_allow_html=True)

if "data" not in st.session_state:
    st.session_state.data = pd.DataFrame(columns=["lat", "lon", "value", "unit", "time"])

# ===============================
# 3. Інтерфейс
# ===============================
st.title("🔵 Моніторинг радіаційної обстановки")

col_map, col_gui = st.columns([2.8, 1])

with col_gui:
    st.subheader("⚙️ Управління")
    
    url_input = st.text_input("Посилання на Google Drive CSV", placeholder="https://drive.google.com/...")
    if st.button("📥 Завантажити з хмари", use_container_width=True):
        if url_input:
            try:
                if '/d/' in url_input:
                    file_id = url_input.split('/d/')[1].split('/')[0]
                else:
                    file_id = url_input.split('id=')[1].split('&')[0]
                direct_link = f'https://drive.google.com/uc?export=download&id={file_id}'
                df_cloud = pd.read_csv(direct_link, sep=None, engine='python')
                st.session_state.data = pd.concat([st.session_state.data, df_cloud], ignore_index=True)
                st.success("Дані оновлено")
                st.rerun()
            except:
                st.error("Помилка посилання або доступу")

    st.divider()

    st.markdown("### 📄 Звітність")
    if not st.session_state.data.empty:
        report_df = st.session_state.data.copy()
        report_df['lat'] = pd.to_numeric(report_df['lat'], errors='coerce')
        report_df['lon'] = pd.to_numeric(report_df['lon'], errors='coerce')
        report_df['value'] = pd.to_numeric(report_df['value'], errors='coerce')
        report_df = report_df.dropna(subset=['lat', 'lon', 'value'])

        if not report_df.empty:
            pdf_bytes = generate_pdf_report(report_df)
            st.download_button(
                label="📊 Завантажити звіт у PDF",
                data=pdf_bytes,
                file_name="radiation_report.pdf",
                mime="application/pdf",
                use_container_width=True
            )
    
    if st.button("🧹 Очистити карту", use_container_width=True):
        st.session_state.data = pd.DataFrame(columns=["lat", "lon", "value", "unit", "time"])
        st.rerun()

# ===============================
# 4. Візуалізація карти (Зі зміною кольору на СИНІЙ)
# ===============================
with col_map:
    if st.session_state.data.empty:
        st.info("Будь ласка, завантажте дані через Google Drive або додайте їх вручну.")
    else:
        df = st.session_state.data.copy()
        for c in ['lat', 'lon', 'value']:
            df[c] = pd.to_numeric(df[c], errors='coerce')
        df = df.dropna(subset=['lat', 'lon', 'value'])
        
        df['time_dt'] = pd.to_datetime(df['time'], dayfirst=True, errors='coerce')
        df['day'] = df['time_dt'].dt.strftime('%d.%m.%Y')
        df.loc[df['day'].isna(), 'day'] = "Інша дата"

        m = folium.Map(location=[df.lat.mean(), df.lon.mean()], zoom_start=10, control_scale=True)
        
        for d in sorted(df['day'].unique()):
            layer = folium.FeatureGroup(name=f"📅 {d}", overlay=True)
            day_data = df[df['day'] == d]

            for _, r in day_data.iterrows():
                val_clean = f"{float(r['value']):.5f}".rstrip('0').rstrip('.')
                txt = f"{val_clean} {r['unit']} | {r['time']}"
                
                # Колір тексту змінено на blue (синій)
                folium.Marker(
                    [r.lat, r.lon],
                    icon=folium.DivIcon(
                        icon_anchor=(-15, 7),
                        html=f'<div style="color:blue; font-family: sans-serif; font-size: 11pt; font-weight: bold; white-space:nowrap;">{txt}</div>'
                    )
                ).add_to(layer)
                
                # Колір точки змінено на blue (синій)
                folium.CircleMarker(
                    [r.lat, r.lon], 
                    radius=7, 
                    color="blue", 
                    fill=True, 
                    fill_color="blue",
                    fill_opacity=0.7
                ).add_to(layer)
            
            layer.add_to(m)

        folium.LayerControl(collapsed=False).add_to(m)
        st_folium(m, width="100%", height=700, key="rad_map_blue")
